myapifilms([{
	"countries": ["USA"],
	"directors": [{"name": "George Lucas", "nameId": "nm0000184"}],
	"filmingLocations": ["Tikal National Park", "Guatemala"],
	"genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"],
	"idIMDB": "tt0076759",
	"languages": ["English"],
	"metascore": "92/100",
	"originalTitle": "Star Wars",
	"plot": "A young boy from Tatooine sets out on an adventure with an old Jedi named Obi-Wan Kenobi as his mentor to save Princess Leia from the ruthless Darth Vader and Destroy the Death Star built by the Empire which has the power to destroy the entire galaxy.",
	"rated": "PG",
	"rating": "8.7",
	"releaseDate": "19770525",
	"runtime": ["121 min"],
	"simplePlot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the universe from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
	"title": "Star Wars: Episode IV - A New Hope",
	"urlIMDB": "http://www.imdb.com/title/tt0076759",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTU4NTczODkwM15BMl5BanBnXkFtZTcwMzEyMTIyMw@@._V1_SX214_AL_.jpg",
	"votes": "772,456",
	"writers": [{"name": "George Lucas", "nameId": "nm0000184"}],
	"year": "1977"
}, {
	"countries": ["USA"],
	"directors": [],
	"filmingLocations": ["Donald C. Tillman Water Reclamation Plant - 6100 Woodley Avenue", "Van Nuys", "Los Angeles", "California", "USA"],
	"genres": ["Action", "Adventure", "Mystery", "Sci-Fi"],
	"idIMDB": "tt0092455",
	"languages": ["English", "Klingon", "French"],
	"metascore": "",
	"originalTitle": "",
	"plot": "Set in the 24th century and decades after the adventures of the original crew of the starship Enterprise, this new series is the long-awaited successor to the original (1966). Under the command of Captain Jean-Luc Picard, the all new Enterprise NCC 1701-D travels out to distant planets to seek out new life and to boldly go where no one has gone before.",
	"rated": "",
	"rating": "8.7",
	"releaseDate": "19870926",
	"runtime": ["44 min"],
	"simplePlot": "Set decades after Captain James T. Kirk's 5-year mission, a new generation of Starfleet officers in a new Enterprise set off on their own mission to go where no one has gone before.",
	"title": "Star Trek: The Next Generation",
	"type": "TV Series",
	"urlIMDB": "http://www.imdb.com/title/tt0092455",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTgyMjY5NTg2NV5BMl5BanBnXkFtZTgwMTAzMDczMDE@._V1_SX214_AL_.jpg",
	"votes": "54,405",
	"writers": [{"name": "Gene Roddenberry", "nameId": "nm0734472"}],
	"year": "1987–1994"
}, {
	"countries": ["USA"],
	"directors": [{"name": "Justin Lin", "nameId": "nm0510912"}],
	"filmingLocations": ["Vancouver", "British Columbia", "Canada"],
	"genres": ["Action", "Adventure", "Sci-Fi", "Thriller"],
	"idIMDB": "tt2660888",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "The plot is unknown at this time.",
	"rated": "",
	"rating": "",
	"releaseDate": "20160708",
	"runtime": [],
	"simplePlot": "The plot is unknown at this time.",
	"title": "Star Trek Beyond",
	"urlIMDB": "http://www.imdb.com/title/tt2660888",
	"urlPoster": "",
	"votes": "",
	"writers": [{"name": "Doug Jung", "nameId": "nm1136647"}, {"name": "Simon Pegg", "nameId": "nm0670408"}],
	"year": "2016"
}, {
	"countries": ["USA"],
	"directors": [{"name": "J.J. Abrams", "nameId": "nm0009190"}],
	"filmingLocations": ["Pinewood Studios", "Iver Heath", "Buckinghamshire", "England", "UK"],
	"genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"],
	"idIMDB": "tt2488496",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "A continuation of the saga created by set thirty years after (1983).",
	"rated": "",
	"rating": "",
	"releaseDate": "20151218",
	"runtime": [],
	"simplePlot": "A continuation of the saga created by George Lucas set thirty years after Star Wars: Episode VI - Return of the Jedi (1983).",
	"title": "Star Wars: Episode VII - The Force Awakens",
	"urlIMDB": "http://www.imdb.com/title/tt2488496",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTUwMjU0MzQwNV5BMl5BanBnXkFtZTgwNzQwODUzNTE@._V1_SX214_AL_.jpg",
	"votes": "",
	"writers": [{"name": "J.J. Abrams", "nameId": "nm0009190"}, {"name": "Lawrence Kasdan", "nameId": "nm0001410"}],
	"year": "2015"
}, {
	"countries": ["USA"],
	"directors": [{"name": "Michael Miller", "nameId": "nm0588964"}],
	"filmingLocations": ["Arden Villa - 1145 Arden Road", "Pasadena", "California", "USA"],
	"genres": ["Drama", "Romance"],
	"idIMDB": "tt0108213",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "After Vietnam, Crystal Wyatt meets a returning soldier, Spencer Hill and although she is young they are drawn together and find they have a lot in common. Spencer's visit is fleeting and although he leaves, Crystal still thinks of him often. Crystal's father dies and her mother, who has never really loved Crystal, begins to mistreat her and use her as a skivvy. After years of this, Crystal is attacked and raped by her brother-in-law. When Crystal gets her father's shotgun to kill her brother-in law, her brother-in-law accidentally shoots her brother, and Crystal runs away from the farm to San Francisco where she becomes quite well known as a singer. Menawhile, Spencer has embarked upon a socially beneficial, yet ill-advised marriage, when he meets Crystal again in San Francisco. They embark on a hurtful affair, but the path does not run smooth for them. As intertwined as their lives are, it takes Spencer time to act like a decent man and do what is right.",
	"rated": "",
	"rating": "5.5",
	"releaseDate": "19930920",
	"runtime": ["120 min"],
	"simplePlot": "After Vietnam, Crystal Wyatt meets a returning soldier, Spencer Hill and although she is young they are drawn together and find they have a lot in common. Spencer's visit is fleeting and ... See full summary »",
	"title": "Star",
	"type": "TV Movie",
	"urlIMDB": "http://www.imdb.com/title/tt0108213",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTQxNDg2MTA4OV5BMl5BanBnXkFtZTcwNDM4OTAyMQ@@._V1_SY317_CR3,0,214,317_AL_.jpg",
	"votes": "508",
	"writers": [{"name": "Claire Labine", "nameId": "nm0479525"}, {"name": "Danielle Steel", "nameId": "nm0824403"}],
	"year": "1993"
}, {
	"countries": ["USA"],
	"directors": [{"name": "Guy Ritchie", "nameId": "nm0005363"}],
	"filmingLocations": ["Los Angeles", "California", "USA"],
	"genres": ["Action", "Short", "Comedy"],
	"idIMDB": "tt0286151",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "The Driver now carries an arrogant rock star who is visiting a major city (not Pittsburgh as earlier believed). Played by Madonna, this title character wants to get away from her bodyguards in the Driver's BMW. He soon gets tired of her and decides to have a bit of fun.",
	"rated": "",
	"rating": "7.8",
	"releaseDate": "200106",
	"runtime": ["7 min"],
	"simplePlot": "The Driver now carries an arrogant rock star who is visiting a major city (not Pittsburgh as earlier believed). Played by Madonna, this title character wants to get away from her bodyguards... See full summary »",
	"title": "Star",
	"urlIMDB": "http://www.imdb.com/title/tt0286151",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTY0NTY2NTUwNV5BMl5BanBnXkFtZTYwNzQxMzg5._V1_SY309_CR1,0,214,309_AL_.jpg",
	"votes": "6,001",
	"writers": [{"name": "Guy Ritchie", "nameId": "nm0005363"}, {"name": "Joe Sweet", "nameId": "nm0996158"}],
	"year": "2001"
}, {
	"countries": ["USA"],
	"directors": [{"name": "Josh Boone", "nameId": "nm1837748"}],
	"filmingLocations": ["Amsterdam", "Noord-Holland", "Netherlands"],
	"genres": ["Drama", "Romance"],
	"idIMDB": "tt2582846",
	"languages": ["English"],
	"metascore": "69/100",
	"originalTitle": "",
	"plot": "Hazel and Augustus are two teenagers who share an acerbic wit, a disdain for the conventional, and a love that sweeps them on a journey. Their relationship is all the more miraculous, given that Hazel's other constant companion is an oxygen tank, Gus jokes about his prosthetic leg, and they meet and fall in love at a cancer support group.",
	"rated": "PG-13",
	"rating": "7.9",
	"releaseDate": "20140606",
	"runtime": ["126 min"],
	"simplePlot": "Two teens, both who have different cancer conditions, fall in love after meeting at a cancer support group.",
	"title": "The Fault in Our Stars",
	"urlIMDB": "http://www.imdb.com/title/tt2582846",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMjA4NzkxNzc5Ml5BMl5BanBnXkFtZTgwNzQ3OTMxMTE@._V1_SY317_CR0,0,214,317_AL_.jpg",
	"votes": "206,429",
	"writers": [{"name": "Scott Neustadter", "nameId": "nm2354099"}, {
		"name": "Michael H. Weber",
		"nameId": "nm2352210"
	}],
	"year": "2014"
}, {
	"countries": ["USA", "Germany"],
	"directors": [{"name": "J.J. Abrams", "nameId": "nm0009190"}],
	"filmingLocations": ["Alaska", "USA"],
	"genres": ["Action", "Adventure", "Sci-Fi"],
	"idIMDB": "tt0796366",
	"languages": ["English"],
	"metascore": "83/100",
	"originalTitle": "",
	"plot": "On the day of James Kirk's birth, his father dies on his ship in a last stand against a mysterious alien time-traveling vessel looking for Ambassador Spock, who, in this time, is also a child on Vulcan disdained by his neighbors for his half-human heritage. Twenty-five years later, Kirk has grown into a young troublemaker. Challenged by Captain Christopher Pike to realize his potential in Starfleet, he comes to annoy instructors like young Commander Spock. Suddenly, there is an emergency at Vulcan and the newly commissioned USS Enterprise is crewed with promising cadets like Nyota Uhura, Hikaru Sulu, Pavel Chekov and even Kirk himself, thanks to Leonard McCoy's medical trickery. Together, this crew will have an adventure in the final frontier where the old legend is altered forever as a new version of it begins.",
	"rated": "PG-13",
	"rating": "8.0",
	"releaseDate": "20090508",
	"runtime": ["127 min"],
	"simplePlot": "The brash James T. Kirk tries to live up to his father's legacy with Mr. Spock keeping him in check as a vengeful, time-traveling Romulan creates black holes to destroy the Federation one planet at a time.",
	"title": "Star Trek",
	"urlIMDB": "http://www.imdb.com/title/tt0796366",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX214_AL_.jpg",
	"votes": "469,586",
	"writers": [{"name": "Roberto Orci", "nameId": "nm0649460"}, {"name": "Alex Kurtzman", "nameId": "nm0476064"}],
	"year": "2009"
}, {
	"countries": ["USA"],
	"directors": [],
	"filmingLocations": ["Backlot", "Desilu Studios - 9336 W. Washington Blvd.", "Culver City", "California", "USA"],
	"genres": ["Action", "Adventure", "Mystery", "Sci-Fi"],
	"idIMDB": "tt0060028",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "The adventures of the USS Enterprise, representing the United Federation of Planets on a five-year mission in outer space to explore new worlds, seek new life and new civilizations, and to boldly go where no man has gone before. The Enterprise is commanded by handsome and brash Captain James T. Kirk. His First Officer and best friend is Mr. Spock from the planet Vulcan, and Kirk's Medical Officer is Dr. Leonard \"Bones\" McCoy. With its crew of approximately 430, the Enterprise battles aliens, megalomanical computers, time paradoxes, psychotic murderers, and even Khan!",
	"rated": "",
	"rating": "8.4",
	"releaseDate": "19660908",
	"runtime": ["50 min"],
	"simplePlot": "Captain James T. Kirk and the crew of the Starship Enterprise explore the Galaxy and defend the United Federation of Planets.",
	"title": "Star Trek",
	"type": "TV Series",
	"urlIMDB": "http://www.imdb.com/title/tt0060028",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTY5MTIxNjkxOF5BMl5BanBnXkFtZTYwNTkyOTE2._V1_SY317_CR1,0,214,317_AL_.jpg",
	"votes": "41,367",
	"writers": [{"name": "Gene Roddenberry", "nameId": "nm0734472"}],
	"year": "1966–1969"
}, {
	"countries": ["USA"],
	"directors": [{"name": "Stuart Heisler", "nameId": "nm0374702"}],
	"filmingLocations": ["Hollywood Boulevard", "Hollywood", "Los Angeles", "California", "USA"],
	"genres": ["Drama", "Romance"],
	"idIMDB": "tt0045186",
	"languages": ["English"],
	"metascore": "",
	"originalTitle": "",
	"plot": "Middle-aged Oscar winning actress Margaret Elliot - Maggie to those that know her - is a Hollywood has-been. Her life is in shambles. She clings to the hope of resurrecting her past movie stardom as a leading ing?nue. No one will hire her, she's penniless with creditors selling off anything that she owns that is of monetary value, and she has no one to turn to that can see her through financially. She has in the past supported her sister and brother-in-law, who still want to use her as their meal ticket. Divorced from her actor husband, she shares joint custody of their teen-aged daughter Gretchen, from who Maggie tries to hide her problems. When it looks as if Maggie has hit rock bottom, Jim Johannsen re-enters her life. Jim, who once had the stage name Barry Lester, got his big break in Hollywood movies by Maggie. He came to the quick realization that he was neither good as an actor or that he wanted to do it as a profession. He now works as a boat parts supplier and mechanic. Jim ...",
	"rated": "APPROVED",
	"rating": "7.4",
	"releaseDate": "19521211",
	"runtime": ["89 min"],
	"simplePlot": "A washed-up movie queen finds romance, but still desires a come-back.",
	"title": "The Star",
	"urlIMDB": "http://www.imdb.com/title/tt0045186",
	"urlPoster": "http://ia.media-imdb.com/images/M/MV5BMTMxODY4MDI0NF5BMl5BanBnXkFtZTcwODMyOTgyMQ@@._V1_SY317_CR37,0,214,317_AL_.jpg",
	"votes": "2,075",
	"writers": [{"name": "Dale Eunson", "nameId": "nm0262368"}, {"name": "Katherine Albert", "nameId": "nm0016534"}],
	"year": "1952"
}])